package org.intellij.markdown

import org.intellij.markdown.flavours.gfm.GFMFlavourDescriptor
import org.intellij.markdown.html.HtmlGenerator
import org.intellij.markdown.parser.MarkdownParser
import org.junit.Test
import kotlin.test.assertEquals

class GfmJvmTest {
    
    private fun doTest(markdown: String, html: String) {
        val flavour = GFMFlavourDescriptor()
        val tree = MarkdownParser(flavour).buildMarkdownTreeFromString(markdown)
        val generated = HtmlGenerator(markdown, tree, flavour, false).generateHtml()
        
        // Normalize by removing <body> tags and newlines
        val normalizedGenerated = generated.replace("<body>", "").replace("</body>", "").replace("\n", "").trim()
        val normalizedExpected = html.replace("\n", "").trim()

        if (normalizedGenerated != normalizedExpected) {
            println("MISMATCH!")
            println("Generated: $normalizedGenerated")
            println("Expected:  $normalizedExpected")
            println("Generated bytes: ${normalizedGenerated.toByteArray().contentToString()}")
            println("Expected bytes:  ${normalizedExpected.toByteArray().contentToString()}")
        }
        
        assertEquals(normalizedExpected, normalizedGenerated)
    }
    
    @Test
    fun testPipeInsideCodeSpanInTableCell() {
        doTest(
            markdown = "| code | description |\n|------|-------------|\n| `a || b` | Either a or b |",
            html = "<table><thead><tr><th>code</th><th>description</th></tr></thead><tbody><tr><td><code>a || b</code></td><td>Either a or b</td></tr></tbody></table>"
        )
    }

    @Test
    fun testEscapedBackticksInTableCell() {
        doTest(
            markdown = "| code | description |\n|------|-------------|\n| \\`code\\` | Escaped backticks |",
            html = "<table><thead><tr><th>code</th><th>description</th></tr></thead><tbody><tr><td>`code`</td><td>Escaped backticks</td></tr></tbody></table>"
        )
    }

    @Test
    fun testLinkWithPipeInUrlInTableCell() {
        doTest(
            markdown = "| link | description |\n|------|-------------|\n| [example](https://example.com?a=1\\|2) | Link with pipe |",
            html = "<table><thead><tr><th>link</th><th>description</th></tr></thead><tbody><tr><td><a href=\"https://example.com?a=1%7C2\">example</a></td><td>Link with pipe</td></tr></tbody></table>"
        )
    }
}
